---
- name: 'Install PowerDNS'
  apt:
    name:
      - 'pdns-server'
      - 'pdns-recursor'
      - "pdns-backend-{{ dns_server_backend }}"
      - 'python3-dnspython'
      - 'dnsutils'
    state: 'present'
    update_cache: true
