---
- name: 'Check input, skip is OK'
  fail:
    msg: 'Unsupported backend!'
  when: dns_server_backend not in supported_backends

- name: 'Install packages'
  include_tasks: "install-{{ ansible_os_family }}.yml"

- name: 'Ensure API settings'
  template:
    src: 'ansible_pdns.conf.j2'
    dest: '/etc/powerdns/pdns.d/ansible_pdns.conf'
  notify:
    - 'restart pdns'

- name: 'Ensure recursor settings'
  template:
    src: 'recursor.conf.j2'
    dest: '/etc/powerdns/recursor.conf'
  notify:
    - 'restart pdns-recursor'
  when: dns_recursor_enabled

- name: 'Enable Authoratative server'
  service:
    name: 'pdns'
    state: 'started'
    enabled: true

- name: 'Enable Recursive server'
  service:
    name: 'pdns-recursor'
    state: 'started'
    enabled: true

- name: 'Create zones'
  include_tasks: 'create_zone.yml'
  loop: "{{ dns_server_zones }}"
  loop_control:
    loop_var: 'zone'
