---
- name: 'Include OS specific vars'
  ansible.builtin.include_vars: "{{ lookup('first_found', dns_server_vars) }}"
  vars:
    dns_server_vars:
      files:
        - "{{ ansible_facts['os_family'] }}{{ ansible_facts['distribution_major_version'] }}.yml"
        - "{{ ansible_facts['os_family'] }}.yml"
      paths:
        - 'vars'
  no_log: true

- name: 'Install PowerDNS'
  ansible.builtin.package:
    name:
      - "{{ dns_server_pdns_auth_pkg }}"
      - "pdns-backend-{{ dns_server_backend }}"
      - "{{ dns_server_python_dns_pkg }}"
      - "{{ dns_server_python_requests_pkg }}"
      - "{{ dns_server_nsupdate_pkg }}"
    state: 'present'

- name: 'Run SELinux tasks'
  ansible.builtin.include_tasks: 'selinux.yml'
  when: ansible_facts['os_family'] == 'RedHat'

- name: 'Set up automatic reverse zone generation'
  when:
    - dns_server_autogen_reverse_dns
    - dns_server_role == 'master'
  block:
    - name: 'Ensure script to generate reverse zones'
      ansible.builtin.copy:
        src: 'genrev.py'
        dest: '/usr/local/bin/pdns_genrev.py'
        mode: 0755
        owner: 'root'
        group: 'root'

    - name: 'Schedule genrating reverse zones'
      ansible.builtin.cron:
        name: 'Generate reverse DNS zones'
        special_time: 'hourly'
        job: '/usr/local/bin/pdns_genrev.py'
        user: 'root'

- name: 'Install PowerDNS'
  ansible.builtin.package:
    name:
      - 'pdns-recursor'
  when: dns_recursor_enabled

- name: 'Ensure conf dirs'
  ansible.builtin.file:
    path: "{{ dir }}"
    state: 'directory'
    mode: 0750
    owner: 'pdns'
    group: 'pdns'
  loop:
    - "{{ dns_server_basedir }}/pdns.d"
    - '/var/lib/powerdns'
  loop_control:
    loop_var: 'dir'

- name: 'Ensure base config'
  ansible.builtin.copy:
    dest: "{{ dns_server_basedir }}/pdns.conf"
    content: |
      # This file is managed with Ansible, your changes will be lost!
      setgid=pdns
      setuid=pdns
      include-dir={{ dns_server_basedir }}/pdns.d
      launch=
    mode: 0644
    owner: 'pdns'
    group: 'pdns'
  notify:
    - 'restart pdns'

- name: 'Remove default BIND config from package'
  ansible.builtin.file:
    path: "{{ dns_server_basedir }}/pdns.d/bind.conf"
    state: 'absent'
  notify:
    - 'restart pdns'

- name: 'Configure SQLite backend'
  block:
    - name: 'Install dependencies'
      ansible.builtin.package:
        name: "{{ dns_server_sqlite_pkg }}"
        state: 'present'
    - name: 'Place config'
      ansible.builtin.copy:
        src: 'pdns_sqlite.conf'
        dest: "{{ dns_server_basedir }}/pdns.d/sqlite.conf"
        mode: 0644
        owner: 'pdns'
        group: 'pdns'
      notify:
        - 'restart pdns'

    - name: 'Collect package version'
      ansible.builtin.package_facts:

    - name: 'Setup SQLite database file'
      ansible.builtin.shell: |
        /usr/bin/sqlite3 \
        /var/lib/powerdns/pdns.sqlite3 < {{ dns_server_sqlite_schema }}
        chown -R pdns:pdns /var/lib/powerdns
      args:
        creates: '/var/lib/powerdns/pdns.sqlite3'

    - name: 'Ensure SELinux file context'
      ansible.builtin.command: restorecon -rv /var/lib/powerdns
      when: ansible_facts['os_family'] == 'RedHat'
  when: dns_server_backend == 'sqlite3' or dns_server_backend == 'sqlite'

- name: 'Configure Mariadb backend'
  block:
    - name: 'Place config'
      ansible.builtin.template:
        src: 'pdns_mysql.conf.j2'
        dest: "{{ dns_server_basedir }}/pdns.d/mysql.conf"
        mode: 0644
        owner: 'pdns'
        group: 'pdns'
      notify:
        - 'restart pdns'
  when: dns_server_backend == 'mysql'

- name: 'Ensure API settings'
  ansible.builtin.template:
    src: 'ansible_pdns.conf.j2'
    dest: "{{ dns_server_basedir }}/pdns.d/ansible_pdns.conf"
    mode: 0644
    owner: 'pdns'
    group: 'pdns'
  notify:
    - 'restart pdns'

- name: 'Ensure recursor settings'
  ansible.builtin.template:
    src: 'recursor.conf.j2'
    dest: "{{ dns_recursor_conf_dir }}/recursor.conf"
    mode: 0644
    owner: "{{ dns_recursor_uid }}"
    group: "{{ dns_recursor_uid }}"
  notify:
    - 'restart pdns-recursor'
  when: dns_recursor_enabled

- name: 'Enable Authoratative server'
  ansible.builtin.service:
    name: 'pdns'
    state: 'started'
    enabled: true

- name: 'Enable Recursive server'
  ansible.builtin.service:
    name: 'pdns-recursor'
    state: 'started'
    enabled: true
  when: dns_recursor_enabled

- name: 'Configure firewalld'
  ansible.posix.firewalld:
    service: 'dns'
    permanent: true
    immediate: true
    state: 'enabled'
  when: ansible_facts['os_family'] == 'RedHat'

- name: 'Flush handlers'
  ansible.builtin.meta: 'flush_handlers'

- name: 'Import TSIG keys'
  ansible.builtin.shell: |
    set +o pipefail
    result=1
    pdnsutil list-tsig-keys | grep '{{ dns_server_tsig_key_name }}. {{ dns_server_tsig_key_algo }}. {{ dns_server_tsig_key_value }}'
    ret=$?
    if [ $ret -eq 1 ]
    then
      pdnsutil import-tsig-key {{ dns_server_tsig_key_name }} {{ dns_server_tsig_key_algo }} '{{ dns_server_tsig_key_value }}'
      result=2
    else
      result=0
    fi
    exit $result
  args:
    executable: '/bin/bash'
  register: 'tsig_key_import'
  changed_when: tsig_key_import['rc'] == 2
  failed_when: tsig_key_import['rc'] == 1
  when:
    - dns_server_tsig_key_name | length > 0
    - dns_server_tsig_key_value | length > 0

- name: 'Create zones'
  ansible.builtin.include_tasks: 'create_zone.yml'
  loop: "{{ dns_server_zones }}"
  loop_control:
    loop_var: 'zone'
