---
- name: Converge
  hosts: all
  vars:
    ansible_python_interpreter: '/usr/bin/python3'
  tasks:
    - name: 'Prepare APT'
      copy:
        dest: '/etc/apt/apt.conf.d/disable_gpg.conf'
        content: |
          Acquire::Check-Valid-Until "false";
          Acquire::AllowInsecureRepositories "true";
          Acquire::AllowDowngradeToInsecureRepositories "true";
    - name: 'Add PowerDNS repo for 4.4.x'
      copy:
        dest: '/etc/apt/sources.list.d/pdns.list'
        content: |
          deb http://repo.powerdns.com/debian buster-rec-44 main
          deb http://repo.powerdns.com/debian buster-auth-44 main
    - name: 'Run role'
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
    - name: 'Register test record'
      nsupdate:
        server: '127.0.0.1'
        port: 5300
        ttl: '60'
        zone: "{{ zone }}"
        record: "some-host"
        value: '192.168.1.1'
        type: 'A'
      register: 'dns_updated'
      retries: 3
      delay: 3
      until: not dns_updated.failed
      loop:
        - 'sub.example.com'
        - '_msdcs.sub.example.com'
        - 'other.example.com'
      loop_control:
        loop_var: 'zone'
