---
- name: Converge
  hosts: all
  vars:
    dns_server_views: true
    dns_server_backend: 'lmdb'
    dns_server_tsig_key_name: 'rndc-key'
    dns_server_tsig_key_value: 'FcE9ugD2zkWy/r5xkLIFZQ=='
    dns_server_tsig_key_algo: 'hmac-md5'
    _dns_server_molecule: true
  tasks:
    - name: 'Run role'
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"

    - name: 'Register NS record'
      community.general.nsupdate:
        server: '127.0.0.1'
        port: 53
        ttl: '60'
        zone: 'sub.example.com'
        record: 'sub.example.com.'
        value: 'some-host.sub.example.com.'
        type: 'NS'
        key_algorithm: "{{ dns_server_tsig_key_algo }}"
        key_name: "{{ dns_server_tsig_key_name }}"
        key_secret: "{{ dns_server_tsig_key_value }}"
      register: 'dns_updated'
      retries: 3
      delay: 3
      until: not dns_updated.failed

    - name: 'Register A record'
      community.general.nsupdate:
        server: '127.0.0.1'
        port: 53
        ttl: '60'
        zone: 'sub.example.com'
        record: 'some-host'
        value: '192.168.1.1'
        type: 'A'
        key_algorithm: "{{ dns_server_tsig_key_algo }}"
        key_name: "{{ dns_server_tsig_key_name }}"
        key_secret: "{{ dns_server_tsig_key_value }}"
      register: 'dns_updated'
      retries: 3
      delay: 3
      until: not dns_updated.failed
