---
- name: Converge
  hosts: all
  vars:
    ansible_python_interpreter: '/usr/bin/python3'
  roles:
    - name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
  tasks:
    - name: 'Register test record'
      nsupdate:
        server: "{{ dns_server_address }}"
        port: "{{ dns_server_port }}"
        ttl: '60'
        zone: "{{ zone }}"
        record: "some-host"
        value: '192.168.1.1'
        type: 'A'
      register: 'dns_updated'
      retries: 3
      delay: 3
      until: not dns_updated.failed
      loop:
        - 'sub.example.com'
        - '_msdcs.sub.example.com'
        - 'other.example.com'
      loop_control:
        loop_var: 'zone'
