---
- name: Converge
  hosts: all
  vars:
    ansible_python_interpreter: '/usr/bin/python3'
    dns_server_tsig_key_name: 'rndc-key'
    dns_server_tsig_key_value: 'FcE9ugD2zkWy/r5xkLIFZQ=='
    dns_server_tsig_key_algo: 'hmac-md5'
  tasks:
    - name: 'Run role'
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
    - name: 'Register test record'
      nsupdate:
        server: '127.0.0.1'
        port: 5300
        ttl: '60'
        zone: "{{ zone }}"
        record: "some-host"
        value: '192.168.1.1'
        type: 'A'
        key_algorithm: "{{ dns_server_tsig_key_algo }}"
        key_name: "{{ dns_server_tsig_key_name }}"
        key_secret: "{{ dns_server_tsig_key_value }}"
      register: 'dns_updated'
      retries: 3
      delay: 3
      until: not dns_updated.failed
      loop:
        - 'sub.example.com'
        - '_msdcs.sub.example.com'
        - 'other.example.com'
      loop_control:
        loop_var: 'zone'
