---
- name: Prepare
  hosts: all
  vars:
    ansible_python_interpreter: '/usr/bin/python3'
  tasks:
    - name: 'Run prepare tasks on RHEL'
      when: ansible_facts['os_family'] == 'RedHat'
      block:
        - name: 'Ensure EPEL'
          ansible.builtin.package:
            name: 'epel-release'
            state: 'present'

        - name: 'Configure PowerDNS repo'
          ansible.builtin.yum_repository:
            name: 'pdns'
            description: 'PowerDNS'
            baseurl: 'http://repo.powerdns.com/el/$basearch/$releasever/auth-50'
            gpgkey: 'https://repo.powerdns.com/FD380FBB-pub.asc'
            state: 'present'

    - name: 'Run prepare tasks on Debian'
      when: ansible_facts['os_family'] == 'Debian'
      block:
        - name: 'Ensure cron and gnupg2'
          ansible.builtin.package:
            name:
              - 'gnupg2'
              - 'cron'
            state: 'present'
            update_cache: true

        - name: 'Get APT GPG key'
          ansible.builtin.get_url:
            url: 'https://repo.powerdns.com/FD380FBB-pub.asc'
            dest: '/etc/apt/keyrings/auth-50-pub.asc'
            owner: 'root'
            group: 'root'
            mode: '0644'

        - name: 'Add PowerDNS repo'
          ansible.builtin.copy:
            dest: '/etc/apt/sources.list.d/pdns.sources'
            mode: 0644
            content: |
               Types: deb
               URIs: http://repo.powerdns.com/debian
               Suites: {{ ansible_facts['distribution_release'] }}-auth-50
               Components: main
               Signed-By: /etc/apt/keyrings/auth-50-pub.asc

        - name: 'Update APT cache'
          ansible.builtin.apt:
            update_cache: true
