---
- name: "Verify"
  hosts: 'all'
  check_mode: true
  gather_facts: false
  tasks:
    - name: 'Check if pdns is running'
      service:
        name: "{{ service }}"
        state: 'started'
      loop:
        - 'pdns'
        - 'pdns-recursor'
      loop_control:
        loop_var: 'service'

    - name: 'Check if test record exists'
      shell: 'host ns.sub.example.com localhost | tail -n1'
      register: 'r'
      check_mode: false
      changed_when: false
      delegate_to: 'molecule-dns'

    - name: 'Check result'
      assert:
        that: r.stdout == 'ns.sub.example.com has address 127.0.0.1'
